services:
  malphas-postgres:
    container_name: malphas-postgres
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=malphas
      - POSTGRES_DB=malphas

volumes:
  postgres-volume: